# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# https://github.com/peripheryapp/periphery/blob/master/.github/workflows/test.yml

on:
  push:

# ❌ VAR expression
env:
  VAR: ${{ true && 'foo' || 'bar' }}
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $VAR
  job-2:
    runs-on: ubuntu-latest
    if: env.VAR == 'foo'
    steps:
      - run: echo $VAR

# ✅ VAR expression
#env:
#  VAR: ${{ true && 'foo' || 'bar' }}
#jobs:
#  job-1:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo $VAR
#  job-2:
#    runs-on: ubuntu-latest
#    if: ${{ env.VAR  }} == 'foo'
#    steps:
#      - run: echo $VAR

# ✅ Plain VAR
#env:
#  VAR: 'foo'
#jobs:
#  job-1:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo $VAR
#  job-2:
#    runs-on: ubuntu-latest
#    if: ${{ env.VAR == 'foo' }}
#    steps:
#      - run: echo $VAR
