# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# https://github.com/peripheryapp/periphery/blob/master/.github/workflows/test.yml

on:
  push:
jobs:
  init:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      NEEDS_CD: ${{ github.ref == 'refs/tags/production' }}
    outputs:
      skip: ${{ steps.skip.outputs.should_skip }}
      needs_ci: ${{ env.NEEDS_CD == 'true' || steps.skip.outputs.should_skip != 'true' }}
      needs_cd: ${{ github.ref == 'refs/tags/production' }}
    steps:
      - name: Check duplicate CI run
        id: skip
        uses: fkirc/skip-duplicate-actions@v5
  ci:
    runs-on: ubuntu-latest
    needs: [init]
    if: needs.init.outputs.needs_ci == 'true'
    steps:
      - run: |
          echo 'skip: ${{ needs.init.outputs.skip }} (${{ needs.init.outputs.skip == 'true' }})'
      - run: |
          echo 'needs_ci: ${{ needs.init.outputs.needs_ci }} (${{ needs.init.outputs.needs_ci == 'true' }})'
      - run: |
          echo 'needs_cd: ${{ needs.init.outputs.needs_cd }} (${{ needs.init.outputs.needs_cd == 'true' }})'
  cd:
    runs-on: ubuntu-latest
    needs: [init, ci]
    if: needs.init.outputs.needs_cd == 'true'
    steps:
      - run: |
          echo 'skip: ${{ needs.init.outputs.skip }} (${{ needs.init.outputs.skip == 'true' }})'
      - run: |
          echo 'needs_ci: ${{ needs.init.outputs.needs_ci }} (${{ needs.init.outputs.needs_ci == 'true' }})'
      - run: |
          echo 'needs_cd: ${{ needs.init.outputs.needs_cd }} (${{ needs.init.outputs.needs_cd == 'true' }})'
