# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# https://github.com/peripheryapp/periphery/blob/master/.github/workflows/test.yml

on:
  push:

env:
  VAR: ${{ true && 'foo' || 'bar' }}
jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      NEEDS_CD: ${{ github.ref == 'refs/tags/production' }}
    outputs:
      skip: ${{ steps.skip.outputs.should_skip }}
      needs_ci: ${{ env.NEEDS_CD || steps.skip.outputs.should_skip != 'true' }}
      needs_cd: ${{ github.ref == 'refs/tags/production' }}
    steps:
      - name: Check duplicate CI run
        id: skip
        uses: fkirc/skip-duplicate-actions@v5
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - run: echo ${{ needs.job-1.outputs.skip }}
      - run: echo ${{ needs.job-1.outputs.needs_ci }}
      - run: echo ${{ needs.job-1.outputs.needs_cd }}
